/**
 * Write docs/ML_REGRESSION_5A.md from the persisted predictions.
 *
 *   npm run ml:report
 *
 * Every number in the report is read from PostgreSQL (the latest ML_PREDICTION per entity and
 * scenario) and from the frozen demo snapshot. Nothing is typed in by hand, so the document
 * cannot quietly disagree with the database it describes. Run `POST /api/ml/route-risk/score`
 * in both scenarios first.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import meta from '../../ml/artifacts/route-risk-xgb-v1.meta.json';
import { prisma } from '../src/lib/prisma';
import { compare, type ComparisonRow, type Scenario } from '../src/services/routeRiskScoring';

const OUT = resolve(__dirname, '../../docs/ML_REGRESSION_5A.md');

const signed = (n: number | null) => (n === null ? '—' : n > 0 ? `+${n}` : String(n));

function table(rows: ComparisonRow[]): string {
  const lines = [
    '| Entity | Demo | ML | Δ (ML − demo) | Demo level | ML level | Top SHAP drivers |',
    '|---|---:|---:|---:|---|---|---|',
  ];
  for (const r of rows) {
    const drivers = r.topFactors
      .slice(0, 3)
      .map((f) => `${f.factor} ${f.direction === 'increases_risk' ? '↑' : '↓'} ${f.contributionPct}%`)
      .join(', ');
    lines.push(
      `| ${r.label} | ${r.demoScore ?? '—'} | ${r.mlScore ?? '—'} | ${signed(r.difference)} | ${r.demoLevel ?? '—'} | ${r.mlLevel ?? '—'} | ${drivers || '—'} |`,
    );
  }
  return lines.join('\n');
}

function summary(rows: ComparisonRow[]): string {
  const paired = rows.filter((r) => r.difference !== null);
  const meanAbs = paired.reduce((s, r) => s + Math.abs(r.difference ?? 0), 0) / Math.max(1, paired.length);
  const sameLevel = paired.filter((r) => r.demoLevel === r.mlLevel).length;
  return `Mean |Δ| ${meanAbs.toFixed(1)} points across ${paired.length} entities; ${sameLevel}/${paired.length} in the same risk band.`;
}

async function main(): Promise<void> {
  const scenarios: Scenario[] = ['baseline', 'heavy_rain'];
  const results = Object.fromEntries(
    await Promise.all(scenarios.map(async (s) => [s, await compare(s)] as const)),
  ) as Record<Scenario, ComparisonRow[]>;

  const route = (s: Scenario, label: string) => results[s].find((r) => r.label === label);
  const a = route('heavy_rain', 'Route A');
  const b = route('heavy_rain', 'Route B');
  const rerouteHolds = a?.mlScore != null && b?.mlScore != null && a.mlScore >= 70 && a.mlScore - b.mlScore >= 15;

  const doc = `# ML regression checkpoint — route-risk-xgb-v1 (Phase 5A)

Generated by \`npm run ml:report\` from the predictions persisted in PostgreSQL. Do not edit by
hand — re-run the scoring endpoint in both scenarios and regenerate.

**What this compares.** "Demo" is the frozen deterministic score the product displays
(web/src/data/demo, exported to world.json). "ML" is the latest \`route-risk-xgb-v1\` prediction
for the same entity in the same scenario, produced by XGBoost from the entity's stored features.
The demo numbers are the regression *reference*; the model was not tuned toward them, and a
difference is a finding, not a defect.

**What it does not show.** Real-world accuracy. The model was trained on synthetic data
(${meta.dataset.rows.toLocaleString()} rows, seed ${meta.dataset.seed}); see ml/MODEL_CARD.md.

## Baseline — Moderate Rainfall

${table(results.baseline)}

${summary(results.baseline)}

## Heavy rain — after the simulated storm

${table(results.heavy_rain)}

${summary(results.heavy_rain)}

## Does the model reach the same decision?

The decision engine reroutes when the assigned route is ≥ 70 and a candidate is at least 15 points
safer. Under heavy rain the model scores Route A **${a?.mlScore ?? '—'}** and Route B
**${b?.mlScore ?? '—'}**: the rule **${rerouteHolds ? 'fires' : 'does not fire'}**, so the model
${rerouteHolds ? 'independently reaches the demo’s Route B recommendation' : 'does NOT reproduce the demo’s Route B recommendation'}.

## Why the numbers differ

1. **The demo scores were authored; the model's are computed.** Phases 2–3 set 21 / 28 / 41 and
   87 / 32 / 64 to tell a story. The model derives its score from each entity's features, and at
   rest Route A's features — the steepest slopes and highest elevation of the three, with the
   longest landslide record — make it riskier than the demo's 21.
2. **Storm weather covers the whole corridor in the database.** The simulated cascade writes the
   same heavy-rain snapshot to all fifteen segments, while the demo raised only the three segments
   around the tuned one. Every segment's ML score therefore rises; the demo's mostly do not.
3. **Segment slopes in the seed are nearly flat.** Phase 4A derived per-segment
   \`terrainSlopeDeg\` by sampling a coarse elevation profile, which leaves most segments at
   0–3°. Mountain segments the demo rates HIGH or CRITICAL (SEG-010, SEG-013) consequently look
   like gentle valley roads to the model. This is a seed-data limitation, not a model error.
4. **The high tail is thin in training.** Under the project's own weighting, a score of 85+
   needs near-maximal conditions on every axis at once. Few synthetic rows reach it, so the model
   rarely predicts CRITICAL.
`;

  writeFileSync(OUT, doc, 'utf8');
  console.log(`wrote ${OUT}`);
  for (const s of scenarios) console.log(`${s}: ${summary(results[s])}`);
  console.log(`reroute rule under heavy rain: ${rerouteHolds ? 'fires' : 'does not fire'} (A ${a?.mlScore}, B ${b?.mlScore})`);
}

main().finally(() => prisma.$disconnect());
